name: GitHub CI
on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env: 
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
      NuGetAPIKey: ${{ secrets.NuGetAPIKey }}
      ProjectName: SingleInstance

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Build
      shell: pwsh
      run: dotnet build -c Release

    - name: Push nuget packages if a new tag is pushed
      if: startsWith(github.ref, 'refs/tags/')
      shell: pwsh
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/HMBSbige/index.json -n GitHub-HMBSbige -u HMBSbige -p ${{ secrets.NUGET_TOKEN }} --store-password-in-clear-text
        dotnet nuget push ${{ env.ProjectName }}\bin\Release\*.nupkg -s GitHub-HMBSbige --skip-duplicate
        dotnet nuget push ${{ env.ProjectName }}\bin\Release\*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NuGetAPIKey }} --skip-duplicate