name: GitHub CI
on: [push, pull_request]

jobs:

  test_linux:
    name: Test on Linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Test .NET Core 3.1
      shell: pwsh
      run: dotnet test --logger:"console;verbosity=detailed" -c Release -f netcoreapp3.1

    - name: Test .NET 5.0
      shell: pwsh
      run: dotnet test --logger:"console;verbosity=detailed" -c Release -f net5.0

  test_windows:
    name: Test on Windows
    needs: test_linux
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Test
      shell: pwsh
      run: dotnet test --logger:"console;verbosity=detailed" -c Release

  build:
    name: Build
    needs: test_windows
    runs-on: ubuntu-latest
    env: 
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
      NuGetAPIKey: ${{ secrets.NuGetAPIKey }}
      ProjectName: SingleInstance

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build
      shell: pwsh
      run: dotnet build -c Release ${{ env.ProjectName }}

    - name: Push nuget packages if a new tag is pushed
      if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
      shell: pwsh
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/HMBSbige/index.json -n GitHub-HMBSbige -u HMBSbige -p ${{ secrets.NUGET_TOKEN }} --store-password-in-clear-text
        dotnet nuget push ${{ env.ProjectName }}\bin\Release\*.nupkg -s GitHub-HMBSbige --skip-duplicate
        dotnet nuget push ${{ env.ProjectName }}\bin\Release\*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NuGetAPIKey }} --skip-duplicate