name: CI
on: [push, pull_request]

jobs:

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Test .NET 4.6.1
      if: startsWith(matrix.os, 'windows-')
      shell: pwsh
      run: dotnet test --logger:"console;verbosity=detailed" -c Release -f net461

    - name: Test .NET Core 3.1
      shell: pwsh
      run: dotnet test --logger:"console;verbosity=detailed" -c Release -f netcoreapp3.1

    - name: Test .NET 5.0
      shell: pwsh
      run: dotnet test --logger:"console;verbosity=detailed" -c Release -f net5.0

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    env: 
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
      NuGetAPIKey: ${{ secrets.NuGetAPIKey }}
      ProjectName: SingleInstance

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Build
      shell: pwsh
      run: dotnet build -c Release

    - name: Push nuget packages if a new tag is pushed
      if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
      shell: pwsh
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/HMBSbige/index.json -n GitHub-HMBSbige -u HMBSbige -p ${{ secrets.NUGET_TOKEN }} --store-password-in-clear-text
        dotnet nuget push ${{ env.ProjectName }}\bin\Release\*.nupkg -s GitHub-HMBSbige --skip-duplicate
        dotnet nuget push ${{ env.ProjectName }}\bin\Release\*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NuGetAPIKey }} --skip-duplicate